/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.seedrocket.hadoop.serialization.thrift;

import org.apache.thrift.TBase;

import org.apache.hadoop.io.serializer.Deserializer;
import org.apache.hadoop.io.serializer.Serialization;
import org.apache.hadoop.io.serializer.Serializer;

/**
 * A {@link Serialization} for types generated by
 * <a href="http://incubator.apache.org/thrift/">Apache Thrift</a>.
 * Thrift types all descend from <code>com.facebook.thrift.TBase</code>.
 * <p>
 * To use this serialization, make sure that the Hadoop property
 * <code>io.serializations</code> includes the fully-qualified classname of this
 * class: <code>org.apache.hadoop.contrib.serialization.thrift.ThriftSerialization</code>.
 */
public class ThriftSerialization implements Serialization<TBase> {

  public boolean accept(Class<?> c) {
    return TBase.class.isAssignableFrom(c);
  }

  public Deserializer<TBase> getDeserializer(Class<TBase> c) {
    return new ThriftDeserializer<TBase>(c);
  }

 public Serializer<TBase> getSerializer(Class<TBase> c) {
    return new ThriftSerializer();
  }

}